##############################################################################
# Description                                                                #
#    Tcl autoload index file, version 2.0 This file is generated by the      #
#    "tixindex" program, *NOT* by the "auto_mkindex" command, and sourced    #
#    to set up indexing information for one or  more commands.               #
#    Typically each line is a command that sets an element in the            #
#    auto_index array, where the element name is the name of a command       #
#    and the value is a script that loads the command.                       #
#                                                                            #
# Revisions                                                                  #
#                                                                            #
#   Date        Who       Reason                                             #
# 01-feb-1999   mnb       Initial                                            #
# 07-Apr-1999   mnb       Added env. variable                                #
# 02-Jun-1999   mnb       Code Integration                                   #
# 07-Sep-1999   mnb       Added CreateFmtPage, CreateAddressPage &           #
#                         CreateBlockPage proceduers to load respective files#
# 21-Sep-1999   mnb       Added ModalityDialog proc to the index             #
# 17-Nov-1999   gsl       Submitted for phase-22.                            #
#                                                                            #
# $HISTORY$                                                                  #
#                                                                            #
##############################################################################

global env
set dir $env(PB_DIR)/ui/
set auto_index(UI_PB_List) "source {$dir/ui_pb_list.tcl}"
set auto_index(UI_PB_MachineTool) "source {$dir/ui_pb_machine.tcl}"
set auto_index(UI_PB_Preview) "source {$dir/ui_pb_preview.tcl}"
set auto_index(UI_PB_Advisor) "source {$dir/ui_pb_advisor.tcl}"
set auto_index(UI_PB_Def) "source {$dir/ui_pb_definition.tcl}"
set auto_index(UI_PB_Def_Block) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_CreateMenuOptions) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_GetBlkAttrSort) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_CreateBlockCells) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_AddBindProcs) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_TrashFocusOn) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_UI_PB_blk_ReturnAddr) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_TrashConnectLine) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_CreatePopupMenu) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_BlockPopupMenu) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_CreateBalloon) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_Def_Address) "source {$dir/ui_pb_address.tcl}"
set auto_index(UI_PB_Def_Format) "source {$dir/ui_pb_format.tcl}"
set auto_index(UI_PB_Def_OtherElements) "source {$dir/ui_pb_others.tcl}"
set auto_index(UI_PB_ProgTpth) "source {$dir/ui_pb_progtpth.tcl}"
set auto_index(UI_PB_ProgTpth_Program) "source {$dir/ui_pb_program.tcl}"
set auto_index(UI_PB_ProgTpth_Gcode) "source {$dir/ui_pb_gcode.tcl}"
set auto_index(UI_PB_ProgTpth_Mcode) "source {$dir/ui_pb_mcode.tcl}"
set auto_index(UI_PB_ProgTpth_WordSeq) "source {$dir/ui_pb_addrseq.tcl}"
set auto_index(UI_PB_ProgTpth_AddSum) "source {$dir/ui_pb_addrsum.tcl}"
set auto_index(UI_PB_evt_ToolPath) "source {$dir/ui_pb_toolpath.tcl}"
set auto_index(UI_PB_ads_CreateSpecialChars) "source {$dir/ui_pb_addrsum.tcl}"
set auto_index(UI_PB_fmt_CreateFmtPage) "source {$dir/ui_pb_format.tcl}"
set auto_index(UI_PB_addr_CreateAddressPage) "source {$dir/ui_pb_address.tcl}"
set auto_index(UI_PB_blk_CreateBlockPage) "source {$dir/ui_pb_block.tcl}"
set auto_index(UI_PB_blk_ModalityDialog) "source {$dir/ui_pb_block.tcl}"
